"""Add bank_account_id to credit_cards

Revision ID: ca7a274755d5
Revises: 61139e02464c
Create Date: 2026-07-26 07:39:28.508662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca7a274755d5'
down_revision: Union[str, None] = '61139e02464c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_credit_cards_bank_account_id', 'bank_accounts', ['bank_account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_cards', schema=None) as batch_op:
        batch_op.drop_constraint('fk_credit_cards_bank_account_id', type_='foreignkey')
        batch_op.drop_column('bank_account_id')
    # ### end Alembic commands ###
